version: "3.9"
services:
    sqlserver:
      build:
        context: .
        dockerfile: ./docker/sqlserver/Dockerfile
      ports:
        - "1434:1433"
      volumes:
        - dbdata:/var/opt/mssql

    aseosbackend:
      build:
        context: .
        dockerfile: ./docker/dotnet/Dockerfile
      ports:
        - "8080:8080"
        - "8081:8081"
      depends_on:
        - sqlserver
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker

volumes:
  dbdata:
