version: "3.9"
services:
    sqlserver:
      build:
        context: .
        dockerfile: ./docker/sqlserver/Dockerfile
      ports:
        - "1434:1433"
      volumes:
        - dbdata:/var/opt/mssql

    aseosbackend:
      build:
        context: .
        dockerfile: ./docker/dotnet/Dockerfile
      ports:
        - "8083:8080"
        - "8084:8081"
      depends_on:
        - sqlserver
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker
    
    aseosfrontend:
      build:
        context: .
        dockerfile: ./docker/angular/Dockerfile
      ports:
        - "4300:4200"
volumes:
  dbdata:
