// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AseoSasBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace AseoSasBackend.Models.Configurations
{
    public partial class CategoriasConfiguration : IEntityTypeConfiguration<Categorias>
    {
        public void Configure(EntityTypeBuilder<Categorias> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC0782EEE7A8");

            entity.Property(e => e.Nombre)
                .HasMaxLength(30)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Categorias> entity);
    }
}
